Q_ENGINE_REPO=../../../../libs/q-engine
IP_LIBRARY_REPO=../../../../libs/ip-library
RISCV_BASEBAND_REPO=../../../../libs/riscv-baseband
# include $(Q_ENGINE_REPO)/scripts/make_include/verilog_paths.mk

include ../build/this_fpga.defs

include ../../../../scripts/make_include/makefile_single_riscv.mk