gtkwave::/Edit/Insert_Comment "ETH"
lappend eth "TOP.tb_higgs_top.eth_top.q_engine_inst.i_ringbus_0"
lappend eth "TOP.tb_higgs_top.eth_top.q_engine_inst.o_ringbus_0"
lappend eth "TOP.tb_higgs_top.eth_top.q_engine_inst.ringbus_0_buf_empty"
lappend eth "TOP.tb_higgs_top.eth_top.q_engine_inst.ringbus_0_interrupt"
lappend eth "TOP.tb_higgs_top.eth_top.q_engine_inst.ringbus_0_interrupt_clear"
lappend eth "TOP.tb_higgs_top.eth_top.q_engine_inst.ringbus_0_rd_of"
lappend eth "TOP.tb_higgs_top.eth_top.q_engine_inst.ringbus_0_read_data"
lappend eth "TOP.tb_higgs_top.eth_top.q_engine_inst.ringbus_0_write_addr"
lappend eth "TOP.tb_higgs_top.eth_top.q_engine_inst.ringbus_0_write_data"
lappend eth "TOP.tb_higgs_top.eth_top.q_engine_inst.ringbus_0_write_done"
lappend eth "TOP.tb_higgs_top.eth_top.q_engine_inst.ringbus_0_write_en"
lappend eth "TOP.tb_higgs_top.eth_top.q_engine_inst.ringbus_0_write_ready"
lappend eth "TOP.tb_higgs_top.eth_top.q_engine_inst.VexRiscv.RegFilePlugin_regFile(16)"
lappend eth "TOP.tb_higgs_top.eth_top.q_engine_inst.VexRiscv.RegFilePlugin_regFile(17)"
set num_added [ gtkwave::addSignalsFromList $eth ]

gtkwave::/Edit/Insert_Comment "CS20"
lappend cs20 "TOP.tb_higgs_top.cs20_top.vex_machine_top_inst.q_engine_inst.i_ringbus_0"
lappend cs20 "TOP.tb_higgs_top.cs20_top.vex_machine_top_inst.q_engine_inst.o_ringbus_0"
lappend cs20 "TOP.tb_higgs_top.cs20_top.vex_machine_top_inst.q_engine_inst.ringbus_0_buf_empty"
lappend cs20 "TOP.tb_higgs_top.cs20_top.vex_machine_top_inst.q_engine_inst.ringbus_0_interrupt"
lappend cs20 "TOP.tb_higgs_top.cs20_top.vex_machine_top_inst.q_engine_inst.ringbus_0_interrupt_clear"
lappend cs20 "TOP.tb_higgs_top.cs20_top.vex_machine_top_inst.q_engine_inst.ringbus_0_rd_of"
lappend cs20 "TOP.tb_higgs_top.cs20_top.vex_machine_top_inst.q_engine_inst.ringbus_0_read_data"
lappend cs20 "TOP.tb_higgs_top.cs20_top.vex_machine_top_inst.q_engine_inst.ringbus_0_write_addr"
lappend cs20 "TOP.tb_higgs_top.cs20_top.vex_machine_top_inst.q_engine_inst.ringbus_0_write_data"
lappend cs20 "TOP.tb_higgs_top.cs20_top.vex_machine_top_inst.q_engine_inst.ringbus_0_write_done"
lappend cs20 "TOP.tb_higgs_top.cs20_top.vex_machine_top_inst.q_engine_inst.ringbus_0_write_en"
lappend cs20 "TOP.tb_higgs_top.cs20_top.vex_machine_top_inst.q_engine_inst.ringbus_0_write_ready"
lappend cs20 "TOP.tb_higgs_top.cs20_top.vex_machine_top_inst.q_engine_inst.VexRiscv.RegFilePlugin_regFile(16)"
lappend cs20 "TOP.tb_higgs_top.cs20_top.vex_machine_top_inst.q_engine_inst.VexRiscv.RegFilePlugin_regFile(17)"
lappend cs20 "TOP.tb_higgs_top.cs20_top.vex_machine_top_inst.riscv_in_data"
lappend cs20 "TOP.tb_higgs_top.cs20_top.vex_machine_top_inst.riscv_in_ready"
lappend cs20 "TOP.tb_higgs_top.cs20_top.vex_machine_top_inst.riscv_in_valid"
lappend cs20 "TOP.tb_higgs_top.cs20_top.vex_machine_top_inst.riscv_out_data"
lappend cs20 "TOP.tb_higgs_top.cs20_top.vex_machine_top_inst.riscv_out_ready"
lappend cs20 "TOP.tb_higgs_top.cs20_top.vex_machine_top_inst.riscv_out_valid"
set num_added [ gtkwave::addSignalsFromList $cs20 ]

gtkwave::/Edit/Insert_Comment "CS10"
lappend cs10 "TOP.tb_higgs_top.cs10_top.vex_machine_top_inst.q_engine_inst.i_ringbus_0"
lappend cs10 "TOP.tb_higgs_top.cs10_top.vex_machine_top_inst.q_engine_inst.o_ringbus_0"
lappend cs10 "TOP.tb_higgs_top.cs10_top.vex_machine_top_inst.q_engine_inst.ringbus_0_buf_empty"
lappend cs10 "TOP.tb_higgs_top.cs10_top.vex_machine_top_inst.q_engine_inst.ringbus_0_interrupt"
lappend cs10 "TOP.tb_higgs_top.cs10_top.vex_machine_top_inst.q_engine_inst.ringbus_0_interrupt_clear"
lappend cs10 "TOP.tb_higgs_top.cs10_top.vex_machine_top_inst.q_engine_inst.ringbus_0_rd_of"
lappend cs10 "TOP.tb_higgs_top.cs10_top.vex_machine_top_inst.q_engine_inst.ringbus_0_read_data"
lappend cs10 "TOP.tb_higgs_top.cs10_top.vex_machine_top_inst.q_engine_inst.ringbus_0_write_addr"
lappend cs10 "TOP.tb_higgs_top.cs10_top.vex_machine_top_inst.q_engine_inst.ringbus_0_write_data"
lappend cs10 "TOP.tb_higgs_top.cs10_top.vex_machine_top_inst.q_engine_inst.ringbus_0_write_done"
lappend cs10 "TOP.tb_higgs_top.cs10_top.vex_machine_top_inst.q_engine_inst.ringbus_0_write_en"
lappend cs10 "TOP.tb_higgs_top.cs10_top.vex_machine_top_inst.q_engine_inst.ringbus_0_write_ready"
lappend cs10 "TOP.tb_higgs_top.cs10_top.vex_machine_top_inst.q_engine_inst.VexRiscv.RegFilePlugin_regFile(16)"
lappend cs10 "TOP.tb_higgs_top.cs10_top.vex_machine_top_inst.q_engine_inst.VexRiscv.RegFilePlugin_regFile(17)"
lappend cs10 "TOP.tb_higgs_top.cs10_top.vex_machine_top_inst.riscv_in_data"
lappend cs10 "TOP.tb_higgs_top.cs10_top.vex_machine_top_inst.riscv_in_ready"
lappend cs10 "TOP.tb_higgs_top.cs10_top.vex_machine_top_inst.riscv_in_valid"
lappend cs10 "TOP.tb_higgs_top.cs10_top.vex_machine_top_inst.riscv_out_data"
lappend cs10 "TOP.tb_higgs_top.cs10_top.vex_machine_top_inst.riscv_out_ready"
lappend cs10 "TOP.tb_higgs_top.cs10_top.vex_machine_top_inst.riscv_out_valid"
set num_added [ gtkwave::addSignalsFromList $cs10 ]

gtkwave::/Edit/Insert_Comment "CS00"
lappend cs00 "TOP.tb_higgs_top.cs00_top.vex_machine_top_inst.q_engine_inst.i_ringbus_0"
lappend cs00 "TOP.tb_higgs_top.cs00_top.vex_machine_top_inst.q_engine_inst.o_ringbus_0"
lappend cs00 "TOP.tb_higgs_top.cs00_top.vex_machine_top_inst.q_engine_inst.ringbus_0_buf_empty"
lappend cs00 "TOP.tb_higgs_top.cs00_top.vex_machine_top_inst.q_engine_inst.ringbus_0_interrupt"
lappend cs00 "TOP.tb_higgs_top.cs00_top.vex_machine_top_inst.q_engine_inst.ringbus_0_interrupt_clear"
lappend cs00 "TOP.tb_higgs_top.cs00_top.vex_machine_top_inst.q_engine_inst.ringbus_0_rd_of"
lappend cs00 "TOP.tb_higgs_top.cs00_top.vex_machine_top_inst.q_engine_inst.ringbus_0_read_data"
lappend cs00 "TOP.tb_higgs_top.cs00_top.vex_machine_top_inst.q_engine_inst.ringbus_0_write_addr"
lappend cs00 "TOP.tb_higgs_top.cs00_top.vex_machine_top_inst.q_engine_inst.ringbus_0_write_data"
lappend cs00 "TOP.tb_higgs_top.cs00_top.vex_machine_top_inst.q_engine_inst.ringbus_0_write_done"
lappend cs00 "TOP.tb_higgs_top.cs00_top.vex_machine_top_inst.q_engine_inst.ringbus_0_write_en"
lappend cs00 "TOP.tb_higgs_top.cs00_top.vex_machine_top_inst.q_engine_inst.ringbus_0_write_ready"
lappend cs00 "TOP.tb_higgs_top.cs00_top.vex_machine_top_inst.q_engine_inst.VexRiscv.RegFilePlugin_regFile(16)"
lappend cs00 "TOP.tb_higgs_top.cs00_top.vex_machine_top_inst.q_engine_inst.VexRiscv.RegFilePlugin_regFile(17)"
lappend cs00 "TOP.tb_higgs_top.cs00_top.vex_machine_top_inst.riscv_in_data"
lappend cs00 "TOP.tb_higgs_top.cs00_top.vex_machine_top_inst.riscv_in_ready"
lappend cs00 "TOP.tb_higgs_top.cs00_top.vex_machine_top_inst.riscv_in_valid"
lappend cs00 "TOP.tb_higgs_top.cs00_top.vex_machine_top_inst.riscv_out_data"
lappend cs00 "TOP.tb_higgs_top.cs00_top.vex_machine_top_inst.riscv_out_ready"
lappend cs00 "TOP.tb_higgs_top.cs00_top.vex_machine_top_inst.riscv_out_valid"
set num_added [ gtkwave::addSignalsFromList $cs00 ]

gtkwave::/Edit/Insert_Comment "CS01"
lappend cs01 "TOP.tb_higgs_top.cs01_top.vex_machine_top_inst.q_engine_inst.i_ringbus_0"
lappend cs01 "TOP.tb_higgs_top.cs01_top.vex_machine_top_inst.q_engine_inst.o_ringbus_0"
lappend cs01 "TOP.tb_higgs_top.cs01_top.vex_machine_top_inst.q_engine_inst.ringbus_0_buf_empty"
lappend cs01 "TOP.tb_higgs_top.cs01_top.vex_machine_top_inst.q_engine_inst.ringbus_0_interrupt"
lappend cs01 "TOP.tb_higgs_top.cs01_top.vex_machine_top_inst.q_engine_inst.ringbus_0_interrupt_clear"
lappend cs01 "TOP.tb_higgs_top.cs01_top.vex_machine_top_inst.q_engine_inst.ringbus_0_rd_of"
lappend cs01 "TOP.tb_higgs_top.cs01_top.vex_machine_top_inst.q_engine_inst.ringbus_0_read_data"
lappend cs01 "TOP.tb_higgs_top.cs01_top.vex_machine_top_inst.q_engine_inst.ringbus_0_write_addr"
lappend cs01 "TOP.tb_higgs_top.cs01_top.vex_machine_top_inst.q_engine_inst.ringbus_0_write_data"
lappend cs01 "TOP.tb_higgs_top.cs01_top.vex_machine_top_inst.q_engine_inst.ringbus_0_write_done"
lappend cs01 "TOP.tb_higgs_top.cs01_top.vex_machine_top_inst.q_engine_inst.ringbus_0_write_en"
lappend cs01 "TOP.tb_higgs_top.cs01_top.vex_machine_top_inst.q_engine_inst.ringbus_0_write_ready"
lappend cs01 "TOP.tb_higgs_top.cs01_top.vex_machine_top_inst.q_engine_inst.VexRiscv.RegFilePlugin_regFile(16)"
lappend cs01 "TOP.tb_higgs_top.cs01_top.vex_machine_top_inst.q_engine_inst.VexRiscv.RegFilePlugin_regFile(17)"
lappend cs01 "TOP.tb_higgs_top.cs01_top.vex_machine_top_inst.riscv_in_data"
lappend cs01 "TOP.tb_higgs_top.cs01_top.vex_machine_top_inst.riscv_in_ready"
lappend cs01 "TOP.tb_higgs_top.cs01_top.vex_machine_top_inst.riscv_in_valid"
lappend cs01 "TOP.tb_higgs_top.cs01_top.vex_machine_top_inst.riscv_out_data"
lappend cs01 "TOP.tb_higgs_top.cs01_top.vex_machine_top_inst.riscv_out_ready"
lappend cs01 "TOP.tb_higgs_top.cs01_top.vex_machine_top_inst.riscv_out_valid"
set num_added [ gtkwave::addSignalsFromList $cs01 ]

gtkwave::/Edit/Insert_Comment "CS11"
lappend cs11 "TOP.tb_higgs_top.cs11_top.vex_machine_top_inst.q_engine_inst.i_ringbus_0"
lappend cs11 "TOP.tb_higgs_top.cs11_top.vex_machine_top_inst.q_engine_inst.o_ringbus_0"
lappend cs11 "TOP.tb_higgs_top.cs11_top.vex_machine_top_inst.q_engine_inst.ringbus_0_buf_empty"
lappend cs11 "TOP.tb_higgs_top.cs11_top.vex_machine_top_inst.q_engine_inst.ringbus_0_interrupt"
lappend cs11 "TOP.tb_higgs_top.cs11_top.vex_machine_top_inst.q_engine_inst.ringbus_0_interrupt_clear"
lappend cs11 "TOP.tb_higgs_top.cs11_top.vex_machine_top_inst.q_engine_inst.ringbus_0_rd_of"
lappend cs11 "TOP.tb_higgs_top.cs11_top.vex_machine_top_inst.q_engine_inst.ringbus_0_read_data"
lappend cs11 "TOP.tb_higgs_top.cs11_top.vex_machine_top_inst.q_engine_inst.ringbus_0_write_addr"
lappend cs11 "TOP.tb_higgs_top.cs11_top.vex_machine_top_inst.q_engine_inst.ringbus_0_write_data"
lappend cs11 "TOP.tb_higgs_top.cs11_top.vex_machine_top_inst.q_engine_inst.ringbus_0_write_done"
lappend cs11 "TOP.tb_higgs_top.cs11_top.vex_machine_top_inst.q_engine_inst.ringbus_0_write_en"
lappend cs11 "TOP.tb_higgs_top.cs11_top.vex_machine_top_inst.q_engine_inst.ringbus_0_write_ready"
lappend cs11 "TOP.tb_higgs_top.cs11_top.vex_machine_top_inst.q_engine_inst.VexRiscv.RegFilePlugin_regFile(16)"
lappend cs11 "TOP.tb_higgs_top.cs11_top.vex_machine_top_inst.q_engine_inst.VexRiscv.RegFilePlugin_regFile(17)"
lappend cs11 "TOP.tb_higgs_top.cs11_top.vex_machine_top_inst.riscv_in_data"
lappend cs11 "TOP.tb_higgs_top.cs11_top.vex_machine_top_inst.riscv_in_ready"
lappend cs11 "TOP.tb_higgs_top.cs11_top.vex_machine_top_inst.riscv_in_valid"
lappend cs11 "TOP.tb_higgs_top.cs11_top.vex_machine_top_inst.riscv_out_data"
lappend cs11 "TOP.tb_higgs_top.cs11_top.vex_machine_top_inst.riscv_out_ready"
lappend cs11 "TOP.tb_higgs_top.cs11_top.vex_machine_top_inst.riscv_out_valid"
set num_added [ gtkwave::addSignalsFromList $cs11 ]

gtkwave::/Edit/Insert_Comment "CS21"
lappend cs21 "TOP.tb_higgs_top.cs21_top.vex_machine_top_inst.q_engine_inst.i_ringbus_0"
lappend cs21 "TOP.tb_higgs_top.cs21_top.vex_machine_top_inst.q_engine_inst.o_ringbus_0"
lappend cs21 "TOP.tb_higgs_top.cs21_top.vex_machine_top_inst.q_engine_inst.ringbus_0_buf_empty"
lappend cs21 "TOP.tb_higgs_top.cs21_top.vex_machine_top_inst.q_engine_inst.ringbus_0_interrupt"
lappend cs21 "TOP.tb_higgs_top.cs21_top.vex_machine_top_inst.q_engine_inst.ringbus_0_interrupt_clear"
lappend cs21 "TOP.tb_higgs_top.cs21_top.vex_machine_top_inst.q_engine_inst.ringbus_0_rd_of"
lappend cs21 "TOP.tb_higgs_top.cs21_top.vex_machine_top_inst.q_engine_inst.ringbus_0_read_data"
lappend cs21 "TOP.tb_higgs_top.cs21_top.vex_machine_top_inst.q_engine_inst.ringbus_0_write_addr"
lappend cs21 "TOP.tb_higgs_top.cs21_top.vex_machine_top_inst.q_engine_inst.ringbus_0_write_data"
lappend cs21 "TOP.tb_higgs_top.cs21_top.vex_machine_top_inst.q_engine_inst.ringbus_0_write_done"
lappend cs21 "TOP.tb_higgs_top.cs21_top.vex_machine_top_inst.q_engine_inst.ringbus_0_write_en"
lappend cs21 "TOP.tb_higgs_top.cs21_top.vex_machine_top_inst.q_engine_inst.ringbus_0_write_ready"
lappend cs21 "TOP.tb_higgs_top.cs21_top.vex_machine_top_inst.q_engine_inst.VexRiscv.RegFilePlugin_regFile(16)"
lappend cs21 "TOP.tb_higgs_top.cs21_top.vex_machine_top_inst.q_engine_inst.VexRiscv.RegFilePlugin_regFile(17)"
lappend cs21 "TOP.tb_higgs_top.cs21_top.vex_machine_top_inst.riscv_in_data"
lappend cs21 "TOP.tb_higgs_top.cs21_top.vex_machine_top_inst.riscv_in_ready"
lappend cs21 "TOP.tb_higgs_top.cs21_top.vex_machine_top_inst.riscv_in_valid"
lappend cs21 "TOP.tb_higgs_top.cs21_top.vex_machine_top_inst.riscv_out_data"
lappend cs21 "TOP.tb_higgs_top.cs21_top.vex_machine_top_inst.riscv_out_ready"
lappend cs21 "TOP.tb_higgs_top.cs21_top.vex_machine_top_inst.riscv_out_valid"
set num_added [ gtkwave::addSignalsFromList $cs21 ]

gtkwave::/Edit/Insert_Comment "CS31"
lappend cs31 "TOP.tb_higgs_top.cs31_top.vex_machine_top_inst.q_engine_inst.i_ringbus_0"
lappend cs31 "TOP.tb_higgs_top.cs31_top.vex_machine_top_inst.q_engine_inst.o_ringbus_0"
lappend cs31 "TOP.tb_higgs_top.cs31_top.vex_machine_top_inst.q_engine_inst.ringbus_0_buf_empty"
lappend cs31 "TOP.tb_higgs_top.cs31_top.vex_machine_top_inst.q_engine_inst.ringbus_0_interrupt"
lappend cs31 "TOP.tb_higgs_top.cs31_top.vex_machine_top_inst.q_engine_inst.ringbus_0_interrupt_clear"
lappend cs31 "TOP.tb_higgs_top.cs31_top.vex_machine_top_inst.q_engine_inst.ringbus_0_rd_of"
lappend cs31 "TOP.tb_higgs_top.cs31_top.vex_machine_top_inst.q_engine_inst.ringbus_0_read_data"
lappend cs31 "TOP.tb_higgs_top.cs31_top.vex_machine_top_inst.q_engine_inst.ringbus_0_write_addr"
lappend cs31 "TOP.tb_higgs_top.cs31_top.vex_machine_top_inst.q_engine_inst.ringbus_0_write_data"
lappend cs31 "TOP.tb_higgs_top.cs31_top.vex_machine_top_inst.q_engine_inst.ringbus_0_write_done"
lappend cs31 "TOP.tb_higgs_top.cs31_top.vex_machine_top_inst.q_engine_inst.ringbus_0_write_en"
lappend cs31 "TOP.tb_higgs_top.cs31_top.vex_machine_top_inst.q_engine_inst.ringbus_0_write_ready"
lappend cs31 "TOP.tb_higgs_top.cs31_top.vex_machine_top_inst.q_engine_inst.VexRiscv.RegFilePlugin_regFile(16)"
lappend cs31 "TOP.tb_higgs_top.cs31_top.vex_machine_top_inst.q_engine_inst.VexRiscv.RegFilePlugin_regFile(17)"
lappend cs31 "TOP.tb_higgs_top.cs31_top.vex_machine_top_inst.riscv_in_data"
lappend cs31 "TOP.tb_higgs_top.cs31_top.vex_machine_top_inst.riscv_in_ready"
lappend cs31 "TOP.tb_higgs_top.cs31_top.vex_machine_top_inst.riscv_in_valid"
lappend cs31 "TOP.tb_higgs_top.cs31_top.vex_machine_top_inst.riscv_out_data"
lappend cs31 "TOP.tb_higgs_top.cs31_top.vex_machine_top_inst.riscv_out_ready"
lappend cs31 "TOP.tb_higgs_top.cs31_top.vex_machine_top_inst.riscv_out_valid"
set num_added [ gtkwave::addSignalsFromList $cs31 ]

gtkwave::/Edit/Insert_Comment "CS30"
lappend cs30 "TOP.tb_higgs_top.cs30_top.vex_machine_top_inst.q_engine_inst.i_ringbus_0"
lappend cs30 "TOP.tb_higgs_top.cs30_top.vex_machine_top_inst.q_engine_inst.o_ringbus_0"
lappend cs30 "TOP.tb_higgs_top.cs30_top.vex_machine_top_inst.q_engine_inst.ringbus_0_buf_empty"
lappend cs30 "TOP.tb_higgs_top.cs30_top.vex_machine_top_inst.q_engine_inst.ringbus_0_interrupt"
lappend cs30 "TOP.tb_higgs_top.cs30_top.vex_machine_top_inst.q_engine_inst.ringbus_0_interrupt_clear"
lappend cs30 "TOP.tb_higgs_top.cs30_top.vex_machine_top_inst.q_engine_inst.ringbus_0_rd_of"
lappend cs30 "TOP.tb_higgs_top.cs30_top.vex_machine_top_inst.q_engine_inst.ringbus_0_read_data"
lappend cs30 "TOP.tb_higgs_top.cs30_top.vex_machine_top_inst.q_engine_inst.ringbus_0_write_addr"
lappend cs30 "TOP.tb_higgs_top.cs30_top.vex_machine_top_inst.q_engine_inst.ringbus_0_write_data"
lappend cs30 "TOP.tb_higgs_top.cs30_top.vex_machine_top_inst.q_engine_inst.ringbus_0_write_done"
lappend cs30 "TOP.tb_higgs_top.cs30_top.vex_machine_top_inst.q_engine_inst.ringbus_0_write_en"
lappend cs30 "TOP.tb_higgs_top.cs30_top.vex_machine_top_inst.q_engine_inst.ringbus_0_write_ready"
lappend cs30 "TOP.tb_higgs_top.cs30_top.vex_machine_top_inst.q_engine_inst.VexRiscv.RegFilePlugin_regFile(16)"
lappend cs30 "TOP.tb_higgs_top.cs30_top.vex_machine_top_inst.q_engine_inst.VexRiscv.RegFilePlugin_regFile(17)"
lappend cs30 "TOP.tb_higgs_top.cs30_top.vex_machine_top_inst.riscv_in_data"
lappend cs30 "TOP.tb_higgs_top.cs30_top.vex_machine_top_inst.riscv_in_ready"
lappend cs30 "TOP.tb_higgs_top.cs30_top.vex_machine_top_inst.riscv_in_valid"
lappend cs30 "TOP.tb_higgs_top.cs30_top.vex_machine_top_inst.riscv_out_data"
lappend cs30 "TOP.tb_higgs_top.cs30_top.vex_machine_top_inst.riscv_out_ready"
lappend cs30 "TOP.tb_higgs_top.cs30_top.vex_machine_top_inst.riscv_out_valid"
set num_added [ gtkwave::addSignalsFromList $cs30 ]