

ifdef TRACE_USE_MINIMAL
TRACE_DISABLE_MAPMOV=1
TRACE_DISABLE_DATAPATH=1
TRACE_DISABLE_DMA_ADJACENT=1
TRACE_DISABLE_ETH_MAC=1
TRACE_DISABLE_MISC=1
TRACE_DISABLE_VEX_INTERNALS=1
endif


DTPBASE=$(HIGGS_ROOT)/sim/hdl/tracing

ifdef TRACE_DISABLE_MAPMOV
DISABLE_TRACING_PATHS+=$(DTPBASE)/disable_mapmov.txt
endif

ifdef TRACE_DISABLE_DATAPATH
DISABLE_TRACING_PATHS+=$(DTPBASE)/disable_datapath.txt
endif

ifdef TRACE_DISABLE_DMA_ADJACENT
DISABLE_TRACING_PATHS+=$(DTPBASE)/disable_dma_adjacent.txt
endif

ifdef TRACE_DISABLE_ETH_MAC
DISABLE_TRACING_PATHS+=$(DTPBASE)/disable_eth_mac.txt
endif

ifdef TRACE_DISABLE_MISC
DISABLE_TRACING_PATHS+=$(DTPBASE)/disable_misc.txt
endif

ifdef TRACE_DISABLE_VEX_INTERNALS
DISABLE_TRACING_PATHS+=$(DTPBASE)/disable_vex_internals.txt
endif
