HIGGS_ROOT = ../../../../../../../..
Q_ENGINE_REPO=$(HIGGS_ROOT)/libs/q-engine
IP_LIBRARY_REPO=$(HIGGS_ROOT)/libs/ip-library
RISCV_BASEBAND_REPO=$(HIGGS_ROOT)/libs/riscv-baseband

include $(HIGGS_ROOT)/scripts/make_include/makefile_single_riscv.mk
