//=============================================================================
// Verilog module generated by IPExpress    
// Filename: USERNAME_inst.v                                          
// Copyright(c) 2006 Lattice Semiconductor Corporation. All rights reserved.   
//=============================================================================

/* WARNING - Changes to this file should be performed by re-running IPexpress
or modifying the .LPC file and regenerating the core.  Other changes may lead
to inconsistent simulation and/or implemenation results */
     gbit_mac DUT_INST ( 

     	  // clock and reset
         .hclk(hclk),
         .txmac_clk(txmac_clk),
         .rxmac_clk(rxmac_clk),
         .reset_n(reset_n),
     
         // Input signals to the GMII
         .rxd(rxd),
         .rx_dv(rx_dv),
         .rx_er(rx_er),
     
         // Input signals to the CPU Interface
         .haddr(haddr),
         .hdatain(hdatain),
         .hcs_n(hcs_n),
         .hwrite_n(hwrite_n),
         .hread_n(hread_n),
     
         // Input signals to the MII Management Interface
     
         // Input signals to the Tx MAC FIFO Interface
         .tx_fifodata(tx_fifodata),
         .tx_fifoavail(tx_fifoavail),
         .tx_fifoeof(tx_fifoeof),
         .tx_fifoempty(tx_fifoempty),
         .tx_sndpaustim(tx_sndpaustim),
         .tx_sndpausreq(tx_sndpausreq),
         .tx_fifoctrl(tx_fifoctrl),
     
         // Input signals to the Rx MAC FIFO Interface
         .rx_fifo_full(rx_fifo_full),
         .ignore_pkt(ignore_pkt),
     
         // Output signals from the GMII
         .txd(txd),
         .tx_en(tx_en),
         .tx_er(tx_er),
     
         // Output signals from the CPU Interface
         .hdataout(hdataout),
         .hdataout_en_n(hdataout_en_n),
         .hready_n(hready_n),
         .cpu_if_gbit_en(cpu_if_gbit_en),
     
         // Output signals from the MII Management Interface
     
         // Output signals from the Tx MAC FIFO Interface
         .tx_macread(tx_macread),
         .tx_discfrm(tx_discfrm),
         .tx_staten(tx_staten),
         .tx_statvec(tx_statvec),
         .tx_done(tx_done),
     
         // Output signals from the Rx MAC FIFO Interface
         .rx_fifo_error(rx_fifo_error),
         .rx_stat_vector(rx_stat_vector),
         .rx_dbout(rx_dbout),
         .rx_write(rx_write),
         .rx_stat_en(rx_stat_en),
         .rx_eof(rx_eof),
         .rx_error(rx_error)
     );
