/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.9.1.119 */
/* Module Version: 5.8 */
/* Thu Nov 02 22:54:47 2017 */

/* parameterized module instance */
dac_tx_2x_ddr __ (.clkout( ), .pll_reset( ), .ready( ), .refclk( ), 
    .sclk( ), .sync_clk( ), .sync_reset( ), .data( ), .dout( ));
