/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.10.0.111.2 */
/* Module Version: 5.7 */
/* Thu Mar 15 10:49:30 2018 */

/* parameterized module instance */
sys_pll __ (.CLKI( ), .CLKOP( ), .CLKOS( ), .LOCK( ));
