/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.9.0.99.2 */
/* Module Version: 5.1 */
/* Tue Apr 04 20:40:53 2017 */

/* parameterized module instance */
big_ass_fifo __ (.Data( ), .Clock( ), .WrEn( ), .RdEn( ), .Reset( ), 
    .Q( ), .Empty( ), .Full( ), .AlmostFull( ));
