/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.10.1.112 */
/* Module Version: 5.7 */
/* Wed Jan 10 21:44:53 2018 */

/* parameterized module instance */
sys_pll __ (.CLKI( ), .PHASESEL( ), .PHASEDIR( ), .PHASESTEP( ), 
    .PHASELOADREG( ), .CLKOP( ), .CLKOS( ), .LOCK( ));
