/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.9.0.99.2 */
/* Module Version: 5.8 */
/* C:\lscc\diamond\3.9_x64\ispfpga\bin\nt64\scuba.exe -w -n ddr_input -lang verilog -synth synplify -bus_exp 7 -bb -arch sa5p00 -type iol -mode Receive -io_type LVCMOS33 -width 5 -freq_in 125 -gear 2 -del 128 -fdc C:/FPGA/gravitinolink/experiments/tempy_temp/ddr_input/ddr_input.fdc  */
/* Wed Mar 01 20:38:01 2017 */


`timescale 1 ns / 1 ps
module ddr_input (clkin, reset, sclk, datain, q)/* synthesis NGD_DRC_MASK=1 */;
    input wire clkin;
    input wire reset;
    input wire [4:0] datain;
    output wire sclk;
    output wire [9:0] q;

    wire buf_clkin;
    wire qb4;
    wire qa4;
    wire qb3;
    wire qa3;
    wire qb2;
    wire qa2;
    wire qb1;
    wire qa1;
    wire qb0;
    wire qa0;
    wire sclk_t;
    wire dataini_t4;
    wire dataini_t3;
    wire dataini_t2;
    wire dataini_t1;
    wire dataini_t0;
    wire buf_dataini4;
    wire buf_dataini3;
    wire buf_dataini2;
    wire buf_dataini1;
    wire buf_dataini0;

    IB Inst3_IB (.I(clkin), .O(buf_clkin))
             /* synthesis IO_TYPE="LVCMOS33" */;

    IDDRX1F Inst2_IDDRX1F4 (.D(dataini_t4), .SCLK(sclk_t), .RST(reset), 
        .Q0(qa4), .Q1(qb4));

    IDDRX1F Inst2_IDDRX1F3 (.D(dataini_t3), .SCLK(sclk_t), .RST(reset), 
        .Q0(qa3), .Q1(qb3));

    IDDRX1F Inst2_IDDRX1F2 (.D(dataini_t2), .SCLK(sclk_t), .RST(reset), 
        .Q0(qa2), .Q1(qb2));

    IDDRX1F Inst2_IDDRX1F1 (.D(dataini_t1), .SCLK(sclk_t), .RST(reset), 
        .Q0(qa1), .Q1(qb1));

    IDDRX1F Inst2_IDDRX1F0 (.D(dataini_t0), .SCLK(sclk_t), .RST(reset), 
        .Q0(qa0), .Q1(qb0));

    defparam udel_dataini4.DEL_MODE = "SCLK_CENTERED" ;
    DELAYG udel_dataini4 (.A(buf_dataini4), .Z(dataini_t4));

    defparam udel_dataini3.DEL_MODE = "SCLK_CENTERED" ;
    DELAYG udel_dataini3 (.A(buf_dataini3), .Z(dataini_t3));

    defparam udel_dataini2.DEL_MODE = "SCLK_CENTERED" ;
    DELAYG udel_dataini2 (.A(buf_dataini2), .Z(dataini_t2));

    defparam udel_dataini1.DEL_MODE = "SCLK_CENTERED" ;
    DELAYG udel_dataini1 (.A(buf_dataini1), .Z(dataini_t1));

    defparam udel_dataini0.DEL_MODE = "SCLK_CENTERED" ;
    DELAYG udel_dataini0 (.A(buf_dataini0), .Z(dataini_t0));

    IB Inst1_IB4 (.I(datain[4]), .O(buf_dataini4))
             /* synthesis IO_TYPE="LVCMOS33" */;

    IB Inst1_IB3 (.I(datain[3]), .O(buf_dataini3))
             /* synthesis IO_TYPE="LVCMOS33" */;

    IB Inst1_IB2 (.I(datain[2]), .O(buf_dataini2))
             /* synthesis IO_TYPE="LVCMOS33" */;

    IB Inst1_IB1 (.I(datain[1]), .O(buf_dataini1))
             /* synthesis IO_TYPE="LVCMOS33" */;

    IB Inst1_IB0 (.I(datain[0]), .O(buf_dataini0))
             /* synthesis IO_TYPE="LVCMOS33" */;

    assign sclk = sclk_t;
    assign q[9] = qb4;
    assign q[8] = qb3;
    assign q[7] = qb2;
    assign q[6] = qb1;
    assign q[5] = qb0;
    assign q[4] = qa4;
    assign q[3] = qa3;
    assign q[2] = qa2;
    assign q[1] = qa1;
    assign q[0] = qa0;
    assign sclk_t = buf_clkin;


    // exemplar begin
    // exemplar attribute Inst3_IB IO_TYPE LVCMOS33
    // exemplar attribute Inst1_IB4 IO_TYPE LVCMOS33
    // exemplar attribute Inst1_IB3 IO_TYPE LVCMOS33
    // exemplar attribute Inst1_IB2 IO_TYPE LVCMOS33
    // exemplar attribute Inst1_IB1 IO_TYPE LVCMOS33
    // exemplar attribute Inst1_IB0 IO_TYPE LVCMOS33
    // exemplar end

endmodule
