/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.9.0.99.2 */
/* Module Version: 5.8 */
/* Wed Mar 01 20:38:01 2017 */

/* parameterized module instance */
ddr_input __ (.clkin( ), .reset( ), .sclk( ), .datain( ), .q( ));
