/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.8.0.115.3 */
/* Module Version: 5.7 */
/* Thu Feb 23 15:19:17 2017 */

/* parameterized module instance */
my_pll __ (.CLKI( ), .CLKOP( ), .LOCK( ));
