/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.9.1.119 */
/* Module Version: 5.7 */
/* Wed Oct 04 16:46:40 2017 */

/* parameterized module instance */
sys_pll __ (.CLKI( ), .PHASESEL( ), .PHASEDIR( ), .PHASESTEP( ), 
    .PHASELOADREG( ), .CLKOP( ), .CLKOS( ), .LOCK( ));
